In [166]:
import pandas as pd
from sklearn.model_selection import train_test_split
from  sklearn.preprocessing import StandardScaler,LabelEncoder
import pickle

In [167]:
data=pd.read_csv("Churn_Modelling.csv")
data.head()

   RowNumber  CustomerId   Surname  ...  IsActiveMember EstimatedSalary Exited
0          1    15634602  Hargrave  ...               1       101348.88      1
1          2    15647311      Hill  ...               1       112542.58      0
2          3    15619304      Onio  ...               0       113931.57      1
3          4    15701354      Boni  ...               0        93826.63      0
4          5    15737888  Mitchell  ...               1        79084.10      0

[5 rows x 14 columns]

In [168]:
## preprocess the data
## drop irrelvant columns
data.drop(["RowNumber","CustomerId","Surname"],axis=1)

      CreditScore Geography  Gender  ...  IsActiveMember  EstimatedSalary  Exited
0             619    France  Female  ...               1        101348.88       1
1             608     Spain  Female  ...               1        112542.58       0
2             502    France  Female  ...               0        113931.57       1
3             699    France  Female  ...               0         93826.63       0
4             850     Spain  Female  ...               1         79084.10       0
...           ...       ...     ...  ...             ...              ...     ...
9995          771    France    Male  ...               0         96270.64       0
9996          516    France    Male  ...               1        101699.77       0
9997          709    France  Female  ...               1         42085.58       1
9998          772   Germany    Male  ...               0         92888.52       1
9999          792    France  Female  ...               0         38190.78       0

[10000 rows x 11 columns]

In [169]:
##Encode categorical variable 
label_encoder_gender=LabelEncoder()
data["Gender"]=label_encoder_gender.fit_transform(data["Gender"])
data

      RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary  Exited
0             1    15634602   Hargrave  ...               1       101348.88       1
1             2    15647311       Hill  ...               1       112542.58       0
2             3    15619304       Onio  ...               0       113931.57       1
3             4    15701354       Boni  ...               0        93826.63       0
4             5    15737888   Mitchell  ...               1        79084.10       0
...         ...         ...        ...  ...             ...             ...     ...
9995       9996    15606229   Obijiaku  ...               0        96270.64       0
9996       9997    15569892  Johnstone  ...               1       101699.77       0
9997       9998    15584532        Liu  ...               1        42085.58       1
9998       9999    15682355  Sabbatini  ...               0        92888.52       1
9999      10000    15628319     Walker  ...               0        38190.78       0

[10000 rows x 14 columns]

In [170]:
## onehot encode "Geography"
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder(sparse_output=False)           # ← renamed param
geo_encoder = onehot_encoder_geo.fit_transform(data[["Geography"]])
geo_encoder_df = pd.DataFrame(geo_encoder,
                              columns=onehot_encoder_geo.get_feature_names_out(["Geography"]))
data = pd.concat([data.drop("Geography", axis=1), geo_encoder_df], axis=1)
data.head()

   RowNumber  CustomerId  ... Geography_Germany  Geography_Spain
0          1    15634602  ...               0.0              0.0
1          2    15647311  ...               0.0              1.0
2          3    15619304  ...               0.0              0.0
3          4    15701354  ...               0.0              0.0
4          5    15737888  ...               0.0              1.0

[5 rows x 16 columns]

In [171]:
with open('lable_encoder_gender.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('onehot_encoder_geo.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

In [172]:
## Divide the dataset into dependent and independent features
X=data.drop(['Exited','RowNumber','CustomerId','Surname'],axis=1)
Y=data["Exited"]

#split the data in training and testing data
x_train ,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

##Scale these features
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]], shape=(8000, 12))

In [173]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

ANN Implementation

In [174]:
import tensorflow as tf
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

In [175]:
## Build ANN Model

model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)), ##Hidden Layer 1 connected with input layer
    Dense(32,activation='relu'), #hidden layer -2
    Dense(1,activation='sigmoid') #output layer
]
)

c:\Users\VenkataSivajiDevarak\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [176]:
model.summary()

Model: "sequential_9"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_27 (Dense)                │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_28 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_29 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [177]:
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
loss=tf.keras.losses.BinaryCrossentropy()
loss

In [178]:
model.compile(optimizer=opt,loss="BinaryCrossentropy",metrics=["accuracy"])

In [179]:
## Set up the Tensorboard
from  tensorflow.keras.callbacks import EarlyStopping,TensorBoard
log_dir="logs/fit/"+datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [180]:
## Set up Early Stopping
early_stopping_callback=EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [181]:
##Train the mode
histroy=model.fit(
    x_train,y_train,validation_data=(x_test,y_test),epochs=100,
    callbacks=[tensorflow_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.8372 - loss: 0.4004 - val_accuracy: 0.8580 - val_loss: 0.3524
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8566 - loss: 0.3589 - val_accuracy: 0.8550 - val_loss: 0.3493
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8570 - loss: 0.3503 - val_accuracy: 0.8525 - val_loss: 0.3469
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8579 - loss: 0.3461 - val_accuracy: 0.8565 - val_loss: 0.3543
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8596 - loss: 0.3419 - val_accuracy: 0.8570 - val_loss: 0.3470
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.8586 - loss: 0.3403 - val_accuracy: 0.8550 - val_loss: 0.3397
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.8624 - loss: 0.3358 - val_accuracy: 0.8555 - val_loss: 0.3459
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8596 - loss: 0.3361 - val_accuracy: 0.8575 - val_loss: 0.3504
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8612 - loss: 0.3336 - val_accuracy: 0.8565 - val_loss: 0.3462
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8631 - loss: 0.3331 - val_accuracy: 0.8600 - val_loss: 0.3435
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8652 - loss: 0.3284 - val_accuracy: 0.8590 - val_loss: 0.3448
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8648 - loss: 0.3269 - val_accuracy: 0.8580 - val_loss: 0.3512
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8664 - loss: 0.3280 - val_accuracy: 0.8585 - val_loss: 0.3416
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8694 - loss: 0.3242 - val_accuracy: 0.8610 - val_loss: 0.3462
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8680 - loss: 0.3242 - val_accuracy: 0.8515 - val_loss: 0.3571
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8665 - loss: 0.3202 - val_accuracy: 0.8580 - val_loss: 0.3562

In [182]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [183]:
#Load Tensorboard Extension
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [184]:
%tensorboard --logdir logs/fit

Reusing TensorBoard on port 6006 (pid 8376), started 0:04:38 ago. (Use '!kill 8376' to kill it.)