In [48]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import numpy as np 
import pandas as pd

In [49]:
##load the trained model , scaler pickle , onehot
from cProfile import label


model=load_model("model.h5")

#load the encoder and scaler
with open('lable_encoder_gender.pkl','rb') as file:
    lable_encoder_gender=pickle.load(file)
with open('onehot_encoder_geo.pkl','rb') as file:
    lable_encoder_geo=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [50]:
input_data={
    "EstimatedSalary":50000,
    "IsActiveMember":1,
    "HasCrCard":1,
    "NumOfProducts":2,
    "Balance":60000,
    "Tenure":3,
    "Age":40,
    "Gender":"Male",
    "CreditScore":600,
    "Geography":"France"

}

In [51]:
geo_encoded=lable_encoder_geo.transform([[input_data["Geography"]]])
geo_encoded_df=pd.DataFrame(geo_encoded,columns=lable_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

c:\Users\VenkataSivajiDevarak\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [52]:
input_df=pd.DataFrame([input_data])
input_df

,EstimatedSalary,IsActiveMember,HasCrCard,NumOfProducts,Balance,Tenure,Age,Gender,CreditScore,Geography
0,50000,1,1,2,60000,3,40,Male,600,France

In [53]:
input_df['Gender']=lable_encoder_gender.transform(input_df['Gender'])

In [54]:
input_df=pd.concat([input_df.drop("Geography",axis=1),geo_encoded_df],axis=1)
input_df

,EstimatedSalary,IsActiveMember,HasCrCard,NumOfProducts,Balance,Tenure,Age,Gender,CreditScore,Geography_France,Geography_Germany,Geography_Spain
0,50000,1,1,2,60000,3,40,1,600,1.0,0.0,0.0

In [56]:
# Reorder to match the column order the scaler was fitted on
input_df = input_df[[
    'CreditScore', 'Gender', 'Age', 'Tenure', 'Balance',
    'NumOfProducts', 'HasCrCard', 'IsActiveMember', 'EstimatedSalary',
    'Geography_France', 'Geography_Germany', 'Geography_Spain'
]]
input_scaled = scaler.transform(input_df)

In [58]:
predication=model.predict(input_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step